### ISSUE TITLE
Formatting bug for class overview page

### ISSUE THREAD

**Issue by kwhinnery** [jsr-io/jsr#239] opened 2024-03-07 22:54 UTC
At the following URL, can see dodgy formatting:

https://jsr.io/@kwhinnery/openai/doc/~/OpenAI

![image](https://github.com/jsr-io/jsr/assets/29193/b01669e8-ee9d-4736-9199-63a3122bc7f2)

**Comment by mary-ext** [comment] 2024-03-07 23:51
dupe of #90

**Closed** 2024-03-08 14:41 UTC
