### ISSUE TITLE
Feature: Add "Use with HTTPS" to user interface

### ISSUE THREAD

**Issue by dbushell** [jsr-io/jsr#679] opened 2024-08-07 04:55 UTC
It would helpful to add a "Use with HTTPS" option since it is possible to import like:

```js
import {encodeBase64} from 'https://jsr.io/@std/encoding/1.0.1/base64.ts';
```

Visual mock-up:

![use-with-http-1x](https://github.com/user-attachments/assets/411111f1-5c43-4d8d-b9af-5611da8fdef5)

This is useful because it is no longer possible to import from source like GitHub:

```js
import * as msgpack from 'https://raw.githubusercontent.com/denoland/std/release-2024.08.05/msgpack/mod.ts';
```

packages with JSR dependencies are broken (latest `std/msgpack` version):

```txt
Uncaught TypeError: Relative import path "@std/bytes/concat" not prefixed with / or ./ or ../
    at https://raw.githubusercontent.com/denoland/std/release-2024.08.05/msgpack/encode.ts:4:24
    at async <anonymous>:1:38
```

where it was possible before pre-JSR (v0.224 `std/msgpack`):

```js
import * as msgpack 'https://raw.githubusercontent.com/denoland/std/0.224.0/msgpack/mod.ts';
```

**Comment by marvinhagemeister** [comment] 2024-08-07 17:37
Duplicate of https://github.com/jsr-io/jsr/issues/133

**Closed by marvinhagemeister** 2024-08-07 17:37 UTC

**Comment by dbushell** [comment] 2024-08-08 05:20
@marvinhagemeister I don't think this is duplicate. #113 is asking for `esm.sh` like browser bundles. I'm refering to server-side HTTP imports the way `deno.land/x` used to work. My suggest is a UI update or some equilevent to surface this on the JSR package page.

They are similar requests, so if both are planned to be tackled at the same time that would be great to see.
