### ISSUE TITLE
markdown table in docs overflows and glitches

### ISSUE THREAD

**Issue by littledivy** [jsr-io/jsr#101] opened 2024-03-01 13:26 UTC
https://jsr.io/@cyclonedx/cdxgen@10.2.1

![image](https://github.com/jsr-io/jsr/assets/34997667/8b286ddd-d3fe-4db9-9e4f-ac8d2beaeb5a)

**Comment by lucacasonato** [comment] 2024-03-04 13:24
Duplicate of #75

**Closed by lucacasonato** 2024-03-04 13:24 UTC
Labels: bug, docs gen
