### ISSUE TITLE
Missing spaces between words in symbol search results.

### ISSUE THREAD

**Issue by canac** [jsr-io/jsr#728] opened 2024-09-15 20:13 UTC
If I search for a symbol, the search results appear to strip whitespace between lines in JSDoc comments. In the screenshot, there is no space between `server` and `and`. In the source, those two words are separated by newlines ([code](https://github.com/denoland/std/blob/58dbbd6bd276d1056f86ef12aa8e034a6be83ca0/http/mod.ts#L3-L4)).

<img width="1225" alt="Screen Shot 2024-09-15 at 3 10 28 PM" src="https://github.com/user-attachments/assets/e5f08ea9-b48b-403d-adf3-14bad831583b">

The space is there on a package's homepage (see screenshot), just not in the symbol search results.

<img width="853" alt="Screen Shot 2024-09-15 at 3 13 09 PM" src="https://github.com/user-attachments/assets/f14b80d2-4e7a-40b2-8365-aa22e515f498">

I couldn't find an existing issue for this, but I apologize if it has been reported before.

**Comment by dandv** [comment] 2024-09-26 05:05
I think this isn't limited to search, but rather a general rendering issue. For example, check [the docs for assert](https://jsr.io/@std/assert/doc):

![image](https://github.com/user-attachments/assets/4b163742-2711-4d62-8f5e-69c52a36dc93)

**Comment by lucacasonato** [comment] 2024-10-28 10:05
Duplicate of #737

**Closed by lucacasonato** 2024-10-28 10:05 UTC
Labels: bug
