### ISSUE TITLE
Feature Request: Yanking an entire package

### ISSUE THREAD

**Issue by andriemc** [jsr-io/jsr#250] opened 2024-03-08 14:15 UTC
Currently, you can only yank one specific version of a package, and depending on the amount of versions in that package, it is gonna take a while, yanking the entire package, wouldn't mean yanking all of the versions, but basically making all of them (including the package) act yanked, so the versions aren't yanked, but the package is, so they'll all act as if they were yanked, and yanked packages could perhaps be hidden in a tab or checkbox when looking at a scope.

**Comment by ry** [comment] 2024-03-08 14:45
I also want this feature. There are likely going to be packages we deprecate from `@std` and I would like a way to prevent them from being displayed on the index page: https://jsr.io/@std

**Comment by lucacasonato** [comment] 2024-03-08 14:51
So I think this is not quite the same as yanking - this is a package level "deprecated". Would do multiple things:

- not show up in search
- not show up in scope overview (except maybe when you check a "show deprecated" checkbox)
- not affect semver resolution like "Yanking" does though

**Comment by roj1512** [comment] 2024-03-08 16:28
Possible duplicate of #208?

**Comment by andriemc** [comment] 2024-03-08 20:43
> > So I think this is not quite the same as yanking - this is a package level "archiving". Would do multiple things:
> > 
> > * not show up in search
> > * not show up in scope overview (except maybe when you check a "show archived" checkbox)
> > * not affect semver resolution like "Yanking" does though
> > 
> > Oh and it would show a warning on the package page that this package is archived.
> 
> yeah, Basically that, maybe also allow adding a optional message? and maybe also send a warning message when installing that package (and maybe also for the usual yanked version feature?) also?
> 
> (Like how currently npm allows you to "deprecate" packages, and basically all npm package managers say it's deprecated, also showing that "optional message" as well.)

The optional message thingy could also be added to yanking individual versions too, since you might want to tell the people who use your package why you yanked that individual version

**Comment by vwkd** [comment] 2024-09-13 13:31
+1 Archiving is also desirable for renaming an old package by creating a new package. As of now at least, renaming a package directly like a GitHub repo isn't possible. Without archiving, the old package clutters the packages list in search and profile creating unnecessary confusion.

**Closed** 2024-09-23 12:49 UTC
Labels: feature
