### ISSUE TITLE
regression: packages pages have wrong offset

### ISSUE THREAD

**Issue by sigmaSd** [jsr-io/jsr#309] opened 2024-03-20 10:09 UTC
for example checkout
- https://jsr.io/packages?page=2
- https://jsr.io/packages?page=3

they have many of the same packages, and this continues on

**Comment by marvinhagemeister** [comment] 2024-03-20 10:49
Maybe it has something to do with caching. Can't reproduce the issue on my end.

**Comment by sigmaSd** [comment] 2024-03-20 13:11
I tried clearing the cache and the issue remain , I also tried on my phone and it's the same result 

![Screenshot_20240320-141015](https://github.com/jsr-io/jsr/assets/22427111/e562cae1-541b-4b6e-b865-ba424eb65558)
![Screenshot_20240320-141003](https://github.com/jsr-io/jsr/assets/22427111/bb7bb052-883c-4d1e-be9b-39c0b4ff01d8)

**Comment by lucacasonato** [comment] 2024-04-02 09:40
This is now fixed.

**Closed by lucacasonato** 2024-04-02 09:40 UTC
Labels: bug
