### ISSUE TITLE
scripts defined in bin are not added to the node_modules/.bin directory

### ISSUE THREAD

**Issue by andeeplus** [jsr-io/jsr#636] opened 2024-07-05 13:26 UTC
- package json modified on publish
- bin field is being stripped from package.json upon publication

When publishing packages to the jsr package registry, it appears that the package.json is being modified, and several fields are being stripped out, including the crucial bin field. This behavior affects the usability of packages intended to provide command-line tools or executables. I couldn't find any information about this behavior in jsr docs, am I missing something?

**Comment by tungv** [comment] 2024-07-07 09:33
I'm not a contributor but I found [this code](https://github.com/jsr-io/jsr/blob/cb7f609d90e32dd6db4f808c0eec0b50b8a072c0/api/src/npm/tarball.rs#L359) that creates a modified version of the package.json for npm compatibility purpose. It doesn't actually change the package.json file you upload, it just creates another version (that overrides your file) when request by an npm client.

The doc does slightly touch this concept [here](https://jsr.io/docs/npm-compatibility#technical-details)

I think we can ask them to add the `scripts` and `bin` fields if they are provided.

**Comment by tungv** [comment] 2024-07-07 09:52
hi @dsherret, is this something the team is working on or we should add a repro here?

**Comment by andeeplus** [comment] 2024-07-08 05:03
Thanks for pointing out the docs @tungv, looks like this is the step where the package json for npm is generated. Definitely having the bin included in there would be great. I can create a repro later on today but probably is not needed due to the clear nature of the issue, @dsherret let me know if needed and I'll provide it, thanks a lot

**Comment by lucacasonato** [comment] 2024-07-12 15:11
Duplicate of https://github.com/jsr-io/jsr/issues/157

**Closed by lucacasonato** 2024-07-12 15:11 UTC
