### ISSUE TITLE
JSR doesn't recognize module docstring if pragma comments come before it

### ISSUE THREAD

**Issue by KyleJune** [jsr-io/jsr#672] opened 2024-07-29 02:41 UTC
The file for my packages server entrypoint has a module docstring but because of this issue, [Support publishing with JSX](https://github.com/jsr-io/jsr/issues/24), I had to manually add pragma comments before it. The [Configuring JSX in Deno](https://docs.deno.com/runtime/manual/advanced/jsx_dom/jsx/) documentation says that pragma comments must come first.

You can see here the module docstring is the first after my pragma comments.
https://jsr.io/@udibo/react-app/0.22.0/server.tsx
![image](https://github.com/user-attachments/assets/3365312f-7844-4331-9a7e-9aa8d93f5531)

You can see it is not showing it here.
https://jsr.io/@udibo/react-app@0.22.0/doc/server/~
![image](https://github.com/user-attachments/assets/e02654a9-e633-4e00-93e2-8160b319996f)

I'm not very familiar with pragma comments, I only know that they are needed from that issue I linked. If it will work and should be after the module docstring, I can move it, although I think it would be a better user experience if it didn't matter which comments came first.

**Comment by lucacasonato** [comment] 2024-10-28 10:17
Duplicate of #605

**Closed by lucacasonato** 2024-10-28 10:17 UTC
Labels: bug, docs gen
