### ISSUE TITLE
Bug: Images in markdown sized incorrectly

### ISSUE THREAD

**Issue by marvinhagemeister** [jsr-io/jsr#245] opened 2024-03-08 09:38 UTC
npm: https://www.npmjs.com/package/@trpc/server

<img width="855" alt="Screenshot 2024-03-08 at 10 35 51" src="https://github.com/jsr-io/jsr/assets/1062408/99a693d0-a571-4fc6-989b-3f9accf92821">

GitHub: https://github.com/trpc/trpc/tree/next/packages/server

<img width="888" alt="Screenshot 2024-03-08 at 10 37 41" src="https://github.com/jsr-io/jsr/assets/1062408/82d6f9c7-d403-47f7-b0ac-692733e613ea">

JSR: https://jsr.io/@trpc/server

<img width="1357" alt="Screenshot 2024-03-08 at 10 36 29" src="https://github.com/jsr-io/jsr/assets/1062408/65709eed-d692-4fc8-9958-6a7f39cd9f00">

**Comment by lucacasonato** [comment] 2024-03-08 09:46
Duplicate of #120

**Closed by lucacasonato** 2024-03-08 09:46 UTC
Labels: UI/UX, docs gen
