### ISSUE TITLE
Documentation with new lines will result in strange formatting

### ISSUE THREAD

**Issue by c43721** [jsr-io/jsr#821] opened 2024-11-07 17:44 UTC
Take the [`@std/fmt`](https://jsr.io/@std/fmt/doc/printf) module as an example:

![image](https://github.com/user-attachments/assets/1bd34431-fdbd-452a-9b6a-10c4750981fb)

When scrolling through the [`docs`](https://jsr.io/@std/fmt/doc#printf), there's sometimes whitespace that's missing. However, if you go to the [symbol docs](https://jsr.io/@std/fmt/doc/printf) the whitespace looks great:

![image](https://github.com/user-attachments/assets/8a207e09-4ddf-42bc-b056-a5a24b134f72)

Notice the `tostdout` has no space between `to` and `stdout` in the first example but does on the second example. This is how it looks in github

![image](https://github.com/user-attachments/assets/ab183a34-eabb-4d2a-bd7a-346b6c86b6de)

And in Visual Studio Code:
![image](https://github.com/user-attachments/assets/bafe9edb-6b12-472c-973b-b0babf2db4ce)

It seems like the problem is the new line, so I think this is a parsing issue.

**Comment by crowlKats** [comment] 2024-11-07 17:50
Duplicate of #737

**Closed by crowlKats** 2024-11-07 17:50 UTC

**Comment by c43721** [comment] 2024-11-07 17:56
Thanks, I'll add some context to that issue.
