### ISSUE TITLE
Feature request: tool for fixing slow types automatically

### ISSUE THREAD

**Issue by kt3k** [jsr-io/jsr#750] opened 2024-10-08 08:39 UTC
I think it's possible to fix slow types automatically by reading the inference result from TSC and adding them to the source code.

**Comment by marvinhagemeister** [comment] 2024-10-08 18:52
Iirc the built-in tsserver in vscode has a command for that.

**Comment by lucacasonato** [comment] 2024-10-28 10:00
Duplicate of #15

**Closed by lucacasonato** 2024-10-28 10:00 UTC
