### ISSUE TITLE
feat: scores are measured at `publish` and `--dry-run`.

### ISSUE THREAD

**Issue by EdamAme-x** [jsr-io/jsr#712] opened 2024-09-04 05:21 UTC
I have to check my score after every release and have to be happy or sad.

```bash
$ deno publish --dry-run

...
Upload ...
...

Score: 96%
 ┣━ JSDoc: 76%
 ┃  ...
 ┗━ Github Actions: ✅
```
(image)

**Comment by marvinhagemeister** [comment] 2024-09-04 13:54
Duplicate of https://github.com/jsr-io/jsr/issues/199

**Closed by marvinhagemeister** 2024-09-04 13:54 UTC
