### ISSUE TITLE
feat: add package changelogs

### ISSUE THREAD

**Issue by okikio** [jsr-io/jsr#756] opened 2024-10-14 07:23 UTC
A number of projects in the ecosystem support changelogs via the `CHANGELOG.md` convention, it would be really cool if `jsr` supported setting a changelog field that pointed to the changelogs of the project and/or supports setting changelogs within the `@module` tsdoc comment.

**Comment by lucacasonato** [comment] 2024-10-28 09:59
Duplicate of #243

**Closed by lucacasonato** 2024-10-28 09:59 UTC
Labels: feature
