### ISSUE TITLE
Package name limited to 20 characters

### ISSUE THREAD

**Issue by piranna** [jsr-io/jsr#129] opened 2024-03-02 13:03 UTC
I'm trying to publish https://github.com/Mafalda-SFU/Remote-Mediasoup-client-mock on jsr.io, but I get an error about `Package name cannot be longer than 20 characters`. Although I can understand there's a limit on the length of a package for usability purposes, it should be an advice and not mandatory, specially if they are packages [already published on npm](https://www.npmjs.com/package/@mafalda-sfu/remote-mediasoup-client-mock), so we should have at least the same limits for compatibility purposes.

**Comment by lucacasonato** [comment] 2024-03-02 13:09
Duplicate of #114

**Closed by lucacasonato** 2024-03-02 13:09 UTC
