### ISSUE TITLE
The version badge displays an outdated version number

### ISSUE THREAD

**Issue by cloydlau** [jsr-io/jsr#456] opened 2024-04-27 07:41 UTC
Reproduction link: https://github.com/cloydlau/json-editor-vue/blob/main/README.md

![image](https://github.com/jsr-io/jsr/assets/31238760/7b27c859-3e2c-4c0e-872b-d5ad175afa51)

I'm not quite sure where the problem is, but the version number of this library is 0.15.0 in jsr, yet it displays 0.13.2.

**Comment by lucacasonato** [comment] 2024-04-27 23:43
Duplicate of https://github.com/jsr-io/jsr/issues/341

**Closed** 2024-04-27 23:43 UTC
